api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import BookReviewViewset 

app_name = 'api'
router = DefaultRouter()
router.register('reviews',BookReviewViewset, basename='review')
urlpatterns = router.urls

goodreads/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from .views import home_page, landing_page

urlpatterns = [
    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('api/', include('api.urls'), name='api'),
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('home', home_page, name='home_page'),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogOutView, ProfileView, ProfileEditView

app_name = 'users'
urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogOutView.as_view(), name='logout'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile_edit', ProfileEditView.as_view(), name='profile_edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    image = models.ImageField(default='default-user-pic.jpg')

users/forms.py
from django import forms
from users.models import CustomUser
from django.core.mail import send_mail

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')
    # /// For forms.form
    # username = forms.CharField(max_length=200)
    # first_name = forms.CharField(max_length=200)
    # last_name = forms.CharField(max_length=200)
    # password = forms.CharField(max_length=128)
    # email = forms.EmailField()

    # def __init__(self, *args, **kwargs):
    #        super().__init__(*args, **kwargs)
    #        self.fields['username'].widget.attrs.update({'class': 'form-control'})
    #        self.fields['password'].widget.attrs.update({'class':'form-control'})

    def save(self, commit = False):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()
        if user.email:
            send_mail(
                'Welcome to Goodreads Clone 🎉🎉🎉',
                f'Hi, {user.username}.Welcome to Goodreads Clone 🎉🎉🎉',
                'akobirtursunov30@gmail.com',
                [user.email], #vajoy99271@ezgiant.com
            )
        return user

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'image')

users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from users.forms import UserCreateForm, ProfileEditForm

# Create your views here.


class RegisterView(View):
    def get(self, request):
        user_form = UserCreateForm()
        context = {'form': user_form}
        return render(request, 'users/register.html', context=context)

    def post(self, request):
        user_form = UserCreateForm(data=request.POST)
        if user_form.is_valid():
            user_form.save()
        # print(f"{username}  {password}")
        else:
            context = {'form': user_form}
            return render(request, 'users/register.html', context=context)

        return redirect('users:login')
    

class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {'login_form': login_form}
        return render(request, 'users/login.html', context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You have successfully logged in.')
        else:
            return render(request, 'users/login.html', {'login_form': login_form})
        return redirect('books:list')


class LogOutView(View):
    def get(self, request):
        logout(request)
        messages.info(request, 'You have successfully logged out!')
        return redirect('landing_page')


class ProfileView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('users:login')
        context = {'user': request.user}
        return render(request, 'users/profile.html', context)


class ProfileEditView(View):
    def get(self, request):
        profile_edit_form = ProfileEditForm(instance=request.user)
        context = {'profile_edit_form': profile_edit_form}
        return render(request, 'users/profile_edit.html', context)

    def post(self, request):
        profile_edit_form = ProfileEditForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
            )
        if profile_edit_form.is_valid:
            profile_edit_form.save()
            messages.success(request, 'Changes are successfully changed.')
        else:
            return render(request, 'users/profile_edit.html', {'profile_edit_form': profile_edit_form})
        return redirect('users:profile')

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login Page {% endblock title %}
{% block content %}
    <h1>Login Page</h1>
    <div class="row">
        <div class="col-4">
            <form method="POST" action="{% url 'users:login' %}">
                {% csrf_token %}
                {{login_form | crispy}}
                <button class='btn btn-primary' type="submit">Submit</button>
                <a class='ms-4' href='{% url 'users:register' %}'>haven't account?</a>
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %} My Profile {% endblock title %}
{% block content %}

<div class="container mt-4 mb-4 p-3 d-flex justify-content-center"> 
    <div class="card profile_card p-4">
        <div class=" image d-flex flex-column justify-content-center align-items-center">
        <button class="btn btn-secondary btnn"> 
            <img src="{{ user.image.url }}" alt='Profile Picture' height="100" width="100" />
        </button>
        <span class="name mt-3 mb-3">{{user.first_name}} {{user.last_name}}</span> 
        <span class="idd mb-2">@{{user.username}}</span> 
        <div class="d-flex f-2 flex-row justify-content-center align-items-center gap-2"> 
            <span class="idd1">{{user.email}}</span> 
            <span><i class="fa fa-copy"></i></span> 
        </div> 
        <div class=" d-flex mt-2"> 
            <button class="btn1 btn-dark"><a href='{% url 'users:profile_edit' %}'>Edit Profile</a></button> 
        </div> 
        <div class=" px-2 rounded mt-4  "> 
            <span class="join">Joined {{user.date_joined | date:"F Y"}}</span> 
        </div> 
    </div> 
</div>
</div>
    {% comment %} <h1>Profile Page</h1>
    <img class="user-pic" src="{{ user.image.url }}" alt='Profile Picture'>
    <div>
        <a href='{% url 'users:profile_edit' %}'>Edit Profile</a>
    </div>
    <p>Username: {{user.username}}</p> 
    <p>First Name: </p> 
    <p>Last Name: {{user.last_name}}</p> 
    <p>Email: {{user.email}}</p>  {% endcomment %}
{% endblock content %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Profile{% endblock title %}

{% block content %}
<h3>Edit Profile</h3>
<div class="row">
    <div class="col-4">
        <form method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            {{profile_edit_form | crispy}}
            <button class='btn btn-primary' type='submit'>Save Changes</button>
        </form>
    </div>
</div>


{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register Page{% endblock title %}
{% block content %}
    <h3>Register</h3>
    <div class="row">
        <div class="col-4">
            <form method="post" action="{% url 'users:register' %}">
                {% csrf_token %}
        
                {{form | crispy}}
                <button class='btn btn-primary' type="submit">Saqlash</button>
                <a class='ms-4' href='{% url 'users:login' %}'> already have account?</a>
        
            </form>
        </div>
    </div>
    

{% endblock content %}