api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import BookReviewViewset 

app_name = 'api'
router = DefaultRouter()
router.register('reviews',BookReviewViewset, basename='review')
urlpatterns = router.urls

books/urls.py
from django.urls import path
from .views import AddReviewView, \
BookDetailView, \
BookListView, \
EditReviewView, \
ConfirmDeleteReviewView, \
DeleteReviewView,  \
AuthorView 

app_name = 'books'
urlpatterns = [
    path('', BookListView.as_view(), name='list'),
    path('<int:id>', BookDetailView.as_view(), name='detail'),
    path('<int:id>/review', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/review/edit', EditReviewView.as_view(), name='review_edit'),
    path('<int:book_id>/reviews/<int:review_id>/review/delete/confirm', ConfirmDeleteReviewView.as_view(), name='review_delete_confirm'),
    path('<int:book_id>/reviews/<int:review_id>/review/delete', DeleteReviewView.as_view(), name='review_delete'),
    path('authors/<int:author_id>', AuthorView.as_view(), name='author_detail'),
]

goodreads/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from .views import home_page, landing_page

urlpatterns = [
    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('api/', include('api.urls'), name='api'),
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('home', home_page, name='home_page'),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogOutView, ProfileView, ProfileEditView

app_name = 'users'
urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogOutView.as_view(), name='logout'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile_edit', ProfileEditView.as_view(), name='profile_edit'),
]

templates/base.html
{% load static %}

{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'books:detail' book.id as books_detail_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile_edit' as profile_edit_page_url %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Goodreads Clone {% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
<body class="mx-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 my-4">
        <div class="container-fluid">
          <a class="navbar-brand me-5" href='{% url 'landing_page' %}'>Goodreads Clone</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll">
              <li class="nav-item">
                <a class="nav-link {% if request.path == home_page_url %}active{% endif %}"  aria-current="page" href="{% url 'home_page' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == books_page_url or request.path == books_detail_url %}active{% endif %}" aria-current="page" href="{% url 'books:list' %}">Books</a>
              </li>
            </ul>
            <div class="d-flex">
                {% if user.is_authenticated %}
                  <div class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle {% if request.path == profile_edit_page_url or request.path == profile_page_url %}active{% endif %}" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {{user.username}}
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                      </ul>
                  </div>
                {% else %}
                  <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Login</a>
                {% endif %}
              </div>
          </div>
        </div>
    </nav>
    <container >
        <div class="my-5">
            {% if messages %}
            {% for message in messages %}
                <span class='alert alert-{{message.tags}}'>{{message}}</span>
            {% endfor %}
        {% endif %}
        </div>
    
        {% block content %}
        {% endblock content %}
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </container>
    
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h2>Home Page</h2>
<div class="container posts-content">
    <div class="row">
    {% for review in page_obj %}
        <div class="col-lg-6 mb-3">
            <div class="card post_card mb-4">
              <div class="card-body">
                <div class="media mb-3">
                  <div class='d-flex align-items-center'>
                    <img class="user-pic me-3" src="{{review.user.image.url}}" alt="">
                    <div class="media-body ml-3">
                      <p>
                        <b>{{review.user.username}}</b>
                        <span> rated this book <b>{{review.stars}} stars</b> </span>
                        <p class="text-muted small">{{review.created_at | date:"D M, Y"}}</p>
                      </p>
                  </div>
                 
                  </div>
                </div>
            
                <p>
                 {{review.review_text}}
                </p>
                <img src="{{review.book.cover_img.url}}" style="margin: 0 auto; display:block" width="200" height="250"/>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <ul class="pagination">
      {% if page_obj.has_previous %}
      {% comment %} <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a> {% endcomment %}
      
      <li class="page-item ">
          <a href="?page=1" class="page-link">&laquo; First</a>
      </li>
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}
      {% if page_obj %}
      <li class="page-item active" aria-current="page">
        <span class="page-link">{{ page_obj.number }}</span>
      </li>
      {% endif %}
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
      </li>
      {% endif %}
    </ul>
  

</div>

{% endblock content %}

templates/landing.html
{% extends 'base.html' %}

{% block content %}
    <h1>About the project</h1>
    <p>Goodreads is an American social cataloging website and a subsidiary of Amazon that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.

        Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler. In December 2007, the site had 650,000 members and 10,000,000 books had been added.By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees. On March 28, 2013, Amazon announced its acquisition of Goodreads, and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.
        
        By July 2019, the site had 90 million members.
    </p>
    <hr>
    <p class='font-italic'>This is a clone website of <a href='https://www.goodreads.com/' target="_blank">Goodreads</a></p>
    <br>
{% endblock content %}