api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import BookReviewViewset 

app_name = 'api'
router = DefaultRouter()
router.register('reviews',BookReviewViewset, basename='review')
urlpatterns = router.urls

books/urls.py
from django.urls import path
from .views import AddReviewView, \
BookDetailView, \
BookListView, \
EditReviewView, \
ConfirmDeleteReviewView, \
DeleteReviewView,  \
AuthorView 

app_name = 'books'
urlpatterns = [
    path('', BookListView.as_view(), name='list'),
    path('<int:id>', BookDetailView.as_view(), name='detail'),
    path('<int:id>/review', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/review/edit', EditReviewView.as_view(), name='review_edit'),
    path('<int:book_id>/reviews/<int:review_id>/review/delete/confirm', ConfirmDeleteReviewView.as_view(), name='review_delete_confirm'),
    path('<int:book_id>/reviews/<int:review_id>/review/delete', DeleteReviewView.as_view(), name='review_delete'),
    path('authors/<int:author_id>', AuthorView.as_view(), name='author_detail'),
]

goodreads/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from .views import home_page, landing_page

urlpatterns = [
    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('api/', include('api.urls'), name='api'),
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('home', home_page, name='home_page'),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.utils import timezone
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.



class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_img = models.ImageField(default='cover.png')
    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    bio = models.TextField(blank=True, null=True)
    author_photo = models.ImageField(default='default-user-pic.jpg')

    def fullName(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f" {self.book.title} {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    stars = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    review_text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.stars} for {self.book.title} by {self.user.username}"

books/forms.py
from django import forms

from books.models import BookReview

class ReviewForm(forms.ModelForm):
    stars = forms.IntegerField(min_value=1, max_value=5)
    class Meta:
        model = BookReview
        fields = ('stars', 'review_text')
        

books/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.urls import reverse
from django.contrib import messages
from django.views.generic import View, ListView, DetailView

from books.forms import ReviewForm
from .models import Author, Book, BookAuthor, BookReview

# Create your views here.

# class BookListView(ListView):
#     template_name = 'books/list.html'
#     queryset = Book.objects.all()
#     context_object_name = 'books'
#     paginate_by = 2


class BookListView(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q', '')
        if search_query:
            books = books.filter(title__icontains = search_query)
        page_size = request.GET.get('page_size', 2)
        pagination = Paginator(books, page_size)

        page_num = request.GET.get('page', 1)
        page_obj = pagination.get_page(page_num)

        context = {'page_obj': page_obj, 'search_query': search_query}
        return render(request, 'books/list.html', context)


# class BookDetailView(DetailView):
#     template_name = 'books/book_detail.html'
#     pk_url_kwarg = 'id'
#     model = Book


class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = ReviewForm()
        context = {'book': book, 'review_form': review_form}
        return render(request, 'books/book_detail.html', context)


class AuthorView(View):
    def get(self, request, author_id):
        author = Author.objects.get(id=author_id)
        own_books_qs = BookAuthor.objects.filter(author=author)
        own_books = [qs.book for qs in own_books_qs]
        context = {
            'author': author,
            'own_books': own_books
        }
        return render(request, 'books/author_about.html', context=context)



class AddReviewView(LoginRequiredMixin,View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = ReviewForm(data=request.POST)
        user = request.user
        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=user,
                stars=review_form.cleaned_data['stars'],
                review_text=review_form.cleaned_data['review_text']
            )
        else:
            context = {'book': book, 'review_form': review_form}
            return render(request, 'books/book_detail.html', context)
        return redirect(reverse('books:detail', kwargs={'id':book.id}))


class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = BookReview.objects.get(id=review_id)
        review_edit_form = ReviewForm(instance=review)

        context = {'book': book, 'review_edit_form': review_edit_form, 'review': review}
        return render(request, 'books/review_edit.html', context)

    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = BookReview.objects.get(id=review_id)
        review_edit_form = ReviewForm(instance=review, data=request.POST)
        
        if review_edit_form.is_valid:
            review_edit_form.save()
        else:
            context = {'book': book, 'review_edit_form': review_edit_form, 'review': review}
            return render(request, 'books/review_edit.html', context)
        return redirect(reverse('books:detail', kwargs={'id': book.id}))


class ConfirmDeleteReviewView(View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        context = {'book': book, 'review': review, }
        return render(request, 'books/review_delete_confirm.html', context)    


class DeleteReviewView(View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review.delete()
        messages.success(request, 'You have successfully deleted the review!')
        return redirect(reverse('books:detail', kwargs={'id': book.id}))

books/templates/books/author_about.html
{% extends 'base.html' %}

{% block title %}About Author{% endblock title %}
{% block content %}
<div class="row mb-5">
    <div class="col-2">
        <img src='{{author.author_photo.url}}' width="150" height="200">
    </div>
    <div class="col-7 ms-5">
        <h3>{{author.fullName}}</h3> 
        <p>{{author.bio}}</p>
        <h4 class='mb-4'>{{author.fullName}}'s books</h4>
        {% for book in own_books %}
            <div class='d-flex gap-2 mb-2'>
                <img src='{{book.cover_img.url}}' width='70' height='90'>
                <h6>{{book.title}}</h6>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

books/templates/books/book_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Book Detail {% endblock title %}  
{% block content %}
    <div class="row mb-5">
        <div class="col-2">
            <img src='{{book.cover_img.url}}' width="250" height="400">
        </div>
        <div class="col-7 ms-5">
            <h3>{{book.title}}</h3>
            {% if book.bookauthor_set.all %}
            <p>Authored by 
                {% for book_author in book.bookauthor_set.all %}
                {% if forloop.last %}
                    <a href="{% url 'books:author_detail' book_author.author.id %}" class='fst-italic fs-5'>{{book_author.author.fullName}}</a>
                {% else %}
                <a href="{% url 'books:author_detail' book_author.author.id %}" class='fst-italic fs-5'>{{book_author.author.fullName}}, </a>
                {% endif %}
                {% endfor %}
                {% endif %}
            <p>{{book.description}}</p>
        </div>
    </div>

    <h3 class='mb-2'>Add Comments</h3>
    <div class="row mb-4">
        <div class="col-7">
            <form action= {% url 'books:reviews' book.id %}  method="post">
                {% csrf_token %}
                {{review_form | crispy}}
                <button class='btn btn-success'>Add Review</button>
            </form>
        </div>
    </div>

    {% if book.bookreview_set.exists %}
    <h2>Reviews</h2><hr>
    {% for review in book.bookreview_set.all %}
    <div class="row mt-5">
        <div class="col-1 me-3">
            <img class="user-pic" src="{{review.user.image.url}}" alt="User image">
        </div>
        <div class="col-8">
            <p class="fs-4">
                <b class="fs-3">{{review.user.username}}</b> rated it <b class="fs-3">{{review.stars}} stars</b> <span class="ms-3 fw-lighter fs-5">{{review.created_at}}</span>
                {% if review.user == request.user %}
                <a href="{% url 'books:review_edit' book.id review.id %}"><i class="bi bi-pen"></i></a>
                <a href="{% url 'books:review_delete_confirm' book.id review.id %}"><i class="bi bi-trash"></i></a>
                {% endif %}
            </p>
            <p class="font-monospace mt-3">{{review.review_text}}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}

{% endblock content %}

books/templates/books/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} All Books {% endblock title %}
{% block content %}
    <h1>Book List</h1>
    <div class="row my-3">
        <div class="col-4">
            <form method="get" class="d-flex">
                <input type="text" class="form-control" placeholder="Search..." name="q" value="{{search_query}}">
                <button class="btn btn-success ms-2">Search</button>
            </form>
        </div>
    </div>
        {% for book in page_obj.object_list %}
            <div class="row mb-5">
                <div class="col-2">
                    <img class="book-pic" src="{{book.cover_img.url}}" alt="Book cover image" width="250" height="250">
                </div>
                <div class="col-4 ms-5 book_info" >
                    <a class=" mb-4 text-bold" href="{% url 'books:detail' book.id %}">{{book.title}}</a>
                    <p>{{book.description | slice:"170"}}.....</p>
                </div>
            </div>
        {% empty %}
        <h5>No Books Found...</h5>
        {% endfor %} 
        <ul class="pagination">
            {% if page_obj.has_previous %}
            {% comment %} <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a> {% endcomment %}
            
            <li class="page-item ">
                <a href="?page=1" class="page-link">&laquo; First</a>
            </li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
            {% if page_obj %}
            <li class="page-item active" aria-current="page">
              <span class="page-link">{{ page_obj.number }}</span>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
            </li>
            {% endif %}
          </ul>
        
        
{% endblock content %}

books/templates/books/review_delete_confirm.html
{% extends 'base.html' %}

{% block content %}

<h3>Are you really sure to delete this review?</h3>
<p><b>Book</b>: {{book.title}}</p>
<p><b>Review</b>: {{review.review_text}}</p>
<hr>
<a href="{% url 'books:review_delete' book.id review.id %}" class='btn btn-outline-danger'>Yes</a>
<a href="{% url 'books:detail' book.id %}" class='btn btn-outline-warning'>No</a>

{% endblock content %}

books/templates/books/review_edit.html
{% extends 'base.html' %}
{% block content %}

{% load crispy_forms_tags %}

<h1>Edit the Review</h1>

<form action= {% url 'books:review_edit' book.id review.id %}  method="post">
    {% csrf_token %}
    {{review_edit_form | crispy}}
    <button class='btn btn-success'>Save</button>
</form>

{% endblock content %}